version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 526056014097.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=526056014097.dkr.ecr.us-east-1.amazonaws.com/devops-app
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating ECS service...
      - aws ecs update-service --cluster devops-cluster --service devops-task-service --force-new-deployment

